routes/web.php
<?php
// Route::get('/', function () {
//     // return view('welcome');
//     return view('chart');
// });

//Public Routing
Route::get('/chart', 'Admin\DashboardController@chart');
Route::get('/', 'RegisterController@create')->name('signup.create');
Route::post('/signup', 'RegisterController@store')->name('signup.store');
Route::get('/notif', 'NotificationController@index')->name('notif');
Route::get('/odojer_name', function($odojer){
	return View::make('chats')->with('odojer_name', $odojer);
});

Auth::routes();

//Private Routing
Route::group(['middleware' => 'admin'],function(){
  Route::get('/dashboard', 'Admin\DashboardController@index')->name('dashboard');
  Route::resource('group', 'Admin\GroupsController');
	Route::resource('program', 'Admin\ProgramsController');
	Route::resource('city', 'Admin\CitiesController');

  //JSON request
  Route::post('/odojer/filter', 'Admin\OdojersController@filterAll')->name('odojer.filter');
  Route::get('/odojer/column/{column}', 'Admin\OdojersController@getByColumn')->name('odojer.gender');
	Route::resource('odojer', 'Admin\OdojersController');

});

app/Odojer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Odojer extends Model
{
    protected $fillable = [
    		'odojer_name',
    		'odojer_address',
    		'odojer_location',
    		'odojer_gender',
    		'odojer_phone',
    		'odojer_status',
    		'program_id',
    		'city_id',
  	];

    public function programs()
    {
        return $this->belongsTo('App\Program', 'program_id');
    }

    public function cities()
    {
        return $this->belongsTo('App\City', 'city_id');
    }


}

app/Http/Controllers/Admin/OdojersController.php
<?php

namespace App\Http\Controllers\Admin;

use DB;
use App\Odojer;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Response;

class OdojersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $odojers = Odojer::with('programs', 'cities')->orderBy('id', 'DESC')->get();
        return view('admin.odojers.list', ['label'=> 'Odojers', 'odojers' => $odojers]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.odojers.form', ['label'=> 'Odojers']);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $odojers = Odojer::create($request->all());
        return redirect()->route('odojer.index')->with('alert-success','Berhasil Menambahkan Data!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $odojers = Odojer::find($id);
        return view('admin.odojers.detail', ['label'=> 'Odojers', 'odojers' => $odojers]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $odojers = Odojer::find($id);
        return view('admin.odojers.form', ['label'=> 'Odojers', 'odojers' => $odojers]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $odojers = Odojer::find($id);
        $odojers->odojer_name       = $request->odojer_name;
        $odojers->odojer_address    = $request->odojer_address;
        $odojers->odojer_location   = $request->odojer_location;
        $odojers->odojer_gender     = $request->odojer_gender;
        $odojers->odojer_phone      = $request->odojer_phone;
        $odojers->odojer_status     = $request->odojer_status;
        $odojers->program_id        = $request->program_id;
        $odojers->city_id           = $request->city_id;
        $odojers->save();

        return redirect()->route('odojer.index')->with('alert-success','Berhasil Memperbarui Data!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $odojer = Odojer::destroy($id);
        return redirect()->route('odojer.index')->with('alert-success','Berhasil Menghapus Data!');
    }

    public function getByColumn($request)
    {
      $odojers = DB::table('odojers')
                ->select($request)
                ->groupBy($request)
                ->get();
      return Response::JSON($odojers);
    }

    public function filterAll(Request $request)
    {
      $filter     = $request->filter;
      $subFilter  = $request->sub_filter;
      $odojers    = DB::table('odojers')
                    ->select('*')
                    ->where($filter, $subFilter)
                    ->get();

      return Response::json($odojers);
    }
}

resources/views/admin/odojers/form.blade.php
@extends('layouts.admin.master')

@section('content')

<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      @if (@$odojers->exists)
          Perbarui Data Anggota
      @else
          Tambah Anggota Baru
      @endif
    </h1>
    <ol class="breadcrumb">
      <li><a href="{{ route('dashboard') }}"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Data {{ $label }}</li>
    </ol>
  </section>

  <section class="content">
    <div class="row">
      <div class="col-xs-12">
        <div class="box">
          <div class="box-header">
            <h3 class="box-title">
            </h3>
            <div class="box-tools">
            </div>
          </div>
          <!-- /.box-header -->
          <div class="box-body">

            @if(@$odojers->exists) <?php  $url = route('odojer.update', @$odojers->id); ?>
            @else <?php  $url = route('odojer.store'); ?>
            @endif
          <form class="form-horizontal" action="{{ $url }}" method="POST">

                @if (@$odojers->exists)
                    {{ method_field('PUT') }}
                @else
                    {{ method_field('POST') }}
                @endif

                {{ csrf_field() }}

                <div class="form-group{{ $errors->has('odojer_name') ? ' has-error' : '' }}">
                    <label for="odojer_name" class="col-md-4 control-label">Name</label>

                    <div class="col-md-6">
                        <input id="odojer_name" type="text" class="form-control" name="odojer_name" value="{{ @$odojers->odojer_name }}" required>

                        @if ($errors->has('odojer_name'))
                            <span class="help-block">
                                <strong>{{ $errors->first('odojer_name') }}</strong>
                            </span>
                        @endif
                    </div>
                </div>

                <div class="form-group{{ $errors->has('odojer_address') ? ' has-error' : '' }}">
                    <label for="odojer_address" class="col-md-4 control-label">Alamat</label>

                    <div class="col-md-6">
                        <input id="odojer_address" type="text" class="form-control" name="odojer_address" value="{{ @$odojers->odojer_address }}"required>

                        @if ($errors->has('odojer_address'))
                            <span class="help-block">
                                <strong>{{ $errors->first('odojer_address') }}</strong>
                            </span>
                        @endif
                    </div>
                </div>

                <div class="form-group{{ $errors->has('odojer_location') ? ' has-error' : '' }}">
                    <label for="odojer_location" class="col-md-4 control-label">Kota/Kabupaten</label>

                    <div class="col-md-6">
                        <input id="odojer_location" type="text" class="form-control" name="odojer_location" value="{{ @$odojers->odojer_location }}"required>

                        @if ($errors->has('odojer_location'))
                            <span class="help-block">
                                <strong>{{ $errors->first('odojer_location') }}</strong>
                            </span>
                        @endif
                    </div>
                </div>

                <div class="form-group{{ $errors->has('odojer_gender') ? ' has-error' : '' }}">
                    <label for="odojer_gender" class="col-md-4 control-label">Jenis Kelamin</label>

                    <div class="col-md-6">
                        <input id="odojer_gender" type="text" class="form-control" name="odojer_gender" value="{{ @$odojers->odojer_gender }}"required>

                        @if ($errors->has('odojer_gender'))
                            <span class="help-block">
                                <strong>{{ $errors->first('odojer_gender') }}</strong>
                            </span>
                        @endif
                    </div>
                </div>

                <div class="form-group{{ $errors->has('odojer_phone') ? ' has-error' : '' }}">
                    <label for="odojer_phone" class="col-md-4 control-label">No. Whatsapp</label>

                    <div class="col-md-6">
                        <input id="odojer_phone" type="text" class="form-control" name="odojer_phone" value="{{ @$odojers->odojer_phone }}"required>

                        @if ($errors->has('odojer_phone'))
                            <span class="help-block">
                                <strong>{{ $errors->first('odojer_phone') }}</strong>
                            </span>
                        @endif
                    </div>
                </div>

                <div class="form-group{{ $errors->has('odojer_status') ? ' has-error' : '' }}">
                    <label for="odojer_status" class="col-md-4 control-label">Status Anggota</label>

                    <div class="col-md-6">
                        <input id="odojer_status" type="text" class="form-control" name="odojer_status" value="{{ @$odojers->odojer_status }}"required>

                        @if ($errors->has('odojer_status'))
                            <span class="help-block">
                                <strong>{{ $errors->first('odojer_status') }}</strong>
                            </span>
                        @endif
                    </div>
                </div>

                <div class="form-group{{ $errors->has('program_id') ? ' has-error' : '' }}">
                    <label for="program_id" class="col-md-4 control-label">Program Pilihan</label>

                    <div class="col-md-6">
                        <input id="program_id" type="text" class="form-control" name="program_id" value="{{ @$odojers->program_id }}"required>

                        @if ($errors->has('program_id'))
                            <span class="help-block">
                                <strong>{{ $errors->first('program_id') }}</strong>
                            </span>
                        @endif
                    </div>
                </div>

                <div class="form-group{{ $errors->has('city_id') ? ' has-error' : '' }}">
                    <label for="city_id" class="col-md-4 control-label">Link Kota</label>

                    <div class="col-md-6">
                        <input id="city_id" type="text" class="form-control" name="city_id" value="{{ @$odojers->city_id }}"required>

                        @if ($errors->has('city_id'))
                            <span class="help-block">
                                <strong>{{ $errors->first('city_id') }}</strong>
                            </span>
                        @endif
                    </div>
                </div>

                <div class="form-group{{ $errors->has('odojer_status') ? ' has-error' : '' }}">
                    <label for="odojer_status" class="col-md-4 control-label">Status</label>

                    <div class="col-md-6">
                        <select class="form-control" name="odojer_status">
                          <?php if (@$odojers->odojer_status == 1): ?>
                            <option value="1" selected>Active</option>
                            <option value="0" >Non Active</option>
                          <?php else: ?>
                            <option value="1" >Active</option>
                            <option value="0" selected>Non Active</option>
                          <?php endif; ?>
                        </select>

                        @if ($errors->has('odojer_status'))
                            <span class="help-block">
                                <strong>{{ $errors->first('odojer_status') }}</strong>
                            </span>
                        @endif
                    </div>
                </div>


                <div class="form-group">
                    <div class="col-md-8 col-md-offset-4">
                        <button type="submit" class="btn btn-success">
                            @if (@$odojers->exists)
                                Update {{ $label }}
                            @else
                                Add {{ $label }}
                            @endif
                        </button>
                        <a class="btn btn-primary" href="{{ route('odojer.index') }}">Back</a>
                    </div>
                </div>
            </form>

          </div>
        </div>
      </div>
    </div>
  </section>

</div>

@endsection

resources/views/admin/odojers/list.blade.php
@extends('layouts.admin.master')

@section('content')
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      List Pendaftaran
    </h1>
    <ol class="breadcrumb">
      <li><a href="{{ route('dashboard') }}"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Data {{ $label }}</li>
    </ol>
  </section>

  <section class="content">
    <div class="row">
      <div class="col-xs-12">
        <div class="box">
          <div class="box-header">
            <h3 class="box-title">
              <a class="btn btn-success" href="{{ route('odojer.create') }}">Create New Odojer</a>
            </h3>
            <div class="box-tools">
              <form id="form-filter" class="" action="" method="post">
                <div id="filter" class="input-group input-group-sm pull-left" style="margin-right:10px">
                  <select id="first" name="filter" class="form-control select2" style="width: 100%;">
                    <option value="odojer_gender" selected="selected">Jenis Kelamin</option>
                    <option value="city_id">Kode Kota</option>
                    <option value="program_id">Program</option>
                    <option value="odojer_status">Status</option>
                  </select>
                </div>
                <div id='sub-filter' class="input-group input-group-sm pull-left" style="margin-right:5px">
                  <select id="second" name="sub_filter" class="form-control select2" style="width: 100%;">
                    <option value="Laki-Laki" selected="selected">Laki-Laki</option>
                    <option value="Perempuan">Perempuan</option>
                  </select>
                </div>
                <div id="submit-filter" class="input-group input-group-sm pull-left" style="margin-right:20px">
                    <button type="submit" class="btn btn-sm btn-default">filter</button>
                </div>
                <div class="input-group input-group-sm" style="width: 150px; ">
                  <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">

                  <div class="input-group-btn">
                    <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                  </div>
                </div>
              </form>
            </div>
          </div>
          <!-- /.box-header -->
          <div class="box-body table-responsive">

            @if(Session::has('alert-success'))
              <div class="alert alert-success" style="background-color:#dff0d8 !important; color:#00a65a !important">
                  <strong>{{ \Illuminate\Support\Facades\Session::get('alert-success') }}</strong>
              </div>
            @endif

            <table class="table table-stripped table-hover">
              <thead>
                <th>#</th>
                <th>Nama</th>
                <th>Alamat</th>
                <th>Kota/Kabupaten</th>
                <th>Jenis Kelamin</th>
                <th>No. Whatsapp</th>
                <th>Status Anggota</th>
                <th>Program Pilihan</th>
                <th>Link Kota</th>
                <th>Opsi</th>
                <th></th>
              </thead>
              <tbody id="#list-odojer">
                @php $no = 1; @endphp
                @foreach ($odojers as $odojer)
                  <tr id="odojer{{$odojer->id}}">
                    <td>{{ $no++ }}</td>
                    <td>{{ $odojer->odojer_name }}</td>
                    <td>{{ $odojer->odojer_address }}</td>
                    <td>{{ $odojer->odojer_location }}</td>
                    <td>{{ $odojer->odojer_gender }}</td>
                    <td>{{ $odojer->odojer_phone }}</td>
                    <td class="text-center">
                      @if($odojer->odojer_status == 1)
                        <label class="label label-success">Active</label>
                      @else
                        <label class="label label-danger">Non active</label>
                      @endif
                    </td>
                    <td>{{ $odojer->programs->program_slug }}</td>
                    <td>{{ $odojer->cities->city_code }}</td>
                    <td>
                      <form action="{{ route('odojer.destroy', $odojer->id) }}" method="post">
                        {{ csrf_field() }}
                        {{ method_field('DELETE') }}
                        <a class="btn btn-sm btn-warning" href="{{ route('odojer.edit', $odojer->id) }}">Edit</a>
                        <button class="btn btn-sm btn-danger" type="submit" onclick="return confirm('Yakin ingin menghapus data?')">Delete</button>
                      </form>
                    </td>
                  </tr>
                @endforeach
              </tbody>
            </table>

          </div>
        </div>
      </div>
    </div>
  </section>

</div>

<meta name="_token" content="{!! csrf_token() !!}" />


@endsection

@section('custom')
<script type="text/javascript">
  var host = window.location.hostname;
  var path = window.location.pathname;

  $("#filter #first").change(function () {
    var str = $("#first option:selected").val();
    var url = 'http://'+host+path+'/column/'+str;

    //request data
    var data = JSON.parse($.ajax({
      type: 'GET',
      url : url,
      dataType:'json',
      global: false,
      async: false,
      success:function(msg){
      }
    }).responseText);
    var htmlStr = "";

    for (var i = 0; i < data.length; i++) {
      var arr = data[i];
      var key = Object.keys(arr);
      var val = Object.values(arr);
      if (key == str) {
        htmlStr = htmlStr + '<option value="'+val+'"> '+ val +' </option>';
      }
      //Memperbarui select sub filter
      $('#sub-filter #second option').remove();
      $('#sub-filter #second').prepend(htmlStr);
    }

  });

  $("#sub-filter #second").change(function () {
    var str = $("#second option:selected").val();
    var url = 'http://'+host+path+'/column/'+str;
    console.log(str);
  });

  $('#submit-filter').click(function(e){
    $.ajaxSetup({
        headers: {
          'X-CSRF-TOKEN': $('meta[name="_token"]').attr('content')
        }
    });
    e.preventDefault();
    var datatosend = $('#form-filter').serialize();
    console.log("datatosend : "+ datatosend);

    $.ajax({
      dataType : 'json',
      type : 'POST',
      url : 'http://'+host+path+'/filter',
      data : datatosend,
      success : function(data) {
        console.log(data);
        $("table tbody tr").remove();

        $.each(data, function(index, element) {
          console.log(element);

          var tabel = '';
          tabel = '<tr id="product' + element.id + '"><td><input type="checkbox" name="id[]" value="22"></td><td>' + element.odojer_name + '</td><td>' + element.odojer_address + '</td><td>' + element.odojer_location + '</td><td>' + element.odojer_gender + '</td><td>' + element.odojer_phone + '</td><td>' + element.odojer_status  + '</td><td>' + element.program_id  + '</td>';
          tabel += '</td><td>' + element.city_id  + '</td>';

          tabel += '<td>'
          tabel += '<form action="http://'+host+path+'/'+element.id+'" method="post">';
          tabel += '{{ csrf_field() }}';
          tabel += '{{ method_field('DELETE') }}';
          tabel += '<a class="btn btn-sm btn-warning" href="http://'+host+path+'/'+element.id+'/edit">Edit</a>';
          tabel += ' <button class="btn btn-sm btn-danger" type="submit" onclick="return confirm(Yakin ingin menghapus data?)">Delete</button>';
          tabel += '</form>';
          tabel += '</td>';
          // tabel += '<td><button class="btn hidden-sm-down btn-info open-modal" value="' + element.id + '">Edit</button> ';
          // tabel += ' <button class="btn hidden-sm-down btn-danger delete-item" value="' + element.id + '">Delete</button></td></tr>';

          // if (state == "add"){ //if user added a new record
          $('table').find('tbody').append(tabel);

        });

      }
    });

  });


</script>
@endsection