routes/web.php
<?php
// Route::get('/', function () {
//     // return view('welcome');
//     return view('chart');
// });

//Public Routing
Route::get('/chart', 'Admin\DashboardController@chart');
Route::get('/', 'RegisterController@create')->name('signup.create');
Route::post('/signup', 'RegisterController@store')->name('signup.store');
Route::get('/notif', 'NotificationController@index')->name('notif');
Route::get('/odojer_name', function($odojer){
	return View::make('chats')->with('odojer_name', $odojer);
});

Auth::routes();

//Private Routing
Route::group(['middleware' => 'admin'],function(){
  Route::get('/dashboard', 'Admin\DashboardController@index')->name('dashboard');
  Route::resource('group', 'Admin\GroupsController');
	Route::resource('program', 'Admin\ProgramsController');
	Route::resource('city', 'Admin\CitiesController');

  //JSON request
  Route::post('/odojer/filter', 'Admin\OdojersController@filterAll')->name('odojer.filter');
  Route::get('/odojer/column/{column}', 'Admin\OdojersController@getByColumn')->name('odojer.gender');
	Route::resource('odojer', 'Admin\OdojersController');

});

app/Program.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Program extends Model
{
    protected $fillable = [
    		'program_name',
    		'program_slug',
    		'program_desc',
  	];

    public function groups() {
  		  return $this->hasMany('App\Group', 'group_program', 'id');
  	}

    public function odojers() {
  		  return $this->hasMany('App\Odojer', 'program_id', 'id');
  	}

}

app/Http/Controllers/Admin/ProgramsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Program;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Response;

class ProgramsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $programs = Program::all();
        return view('admin.programs.list', ['label'=> 'Programs', 'programs' => $programs]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.programs.form', ['label'=> 'Programs']);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $programs = Program::create($request->all());
        return redirect()->route('program.index')->with('alert-success','Berhasil Menambahkan Data!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $programs = Program::find($id);
        return view('admin.programs.detail', ['label'=> 'Programs', 'programs' => $programs]);   
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $programs = Program::find($id);
        return view('admin.programs.form', ['label'=> 'Programs', 'programs' => $programs]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $programs = Program::find($id);
        $programs->program_name = $request->program_name;
        $programs->program_slug = $request->program_slug;
        $programs->program_desc = $request->program_desc;
        $programs->save();

        return redirect()->route('program.index')->with('alert-success','Berhasil Memperbarui Data!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $programs = Program::destroy($id);
        return redirect()->route('program.index')->with('alert-success','Berhasil Menghapus Data!'); 
    }
}

resources/views/admin/programs/form.blade.php
@extends('layouts.admin.master')

@section('content')
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      @if (@$odojers->exists)
          Perbarui Program
      @else
          Tambah Program
      @endif
    </h1>
    <ol class="breadcrumb">
      <li><a href="{{ route('dashboard') }}"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Data {{ $label }}</li>
    </ol>
  </section>

  <section class="content">
    <div class="row">
      <div class="col-xs-12">
        <div class="box">
          <div class="box-header">
            <h3 class="box-title">
            </h3>
            <div class="box-tools">

            </div>
          </div>
          <!-- /.box-header -->
          <div class="box-body">

              @if(@$programs->exists) <?php  $url = route('program.update', @$programs->id); ?>
              @else <?php  $url = route('program.store'); ?>
              @endif
              <form class="form-horizontal" action="{{ $url }}" method="POST">

                @if (@$programs->exists)
                    {{ method_field('PUT') }}
                @else
                    {{ method_field('POST') }}
                @endif

                {{ csrf_field() }}

                <div class="form-group{{ $errors->has('program_name') ? ' has-error' : '' }}">
                    <label for="program_name" class="col-md-4 control-label">Name</label>

                    <div class="col-md-6">
                        <input id="program_name" type="text" class="form-control" name="program_name" value="{{ @$programs->program_name }}" required>

                        @if ($errors->has('program_name'))
                            <span class="help-block">
                                <strong>{{ $errors->first('program_name') }}</strong>
                            </span>
                        @endif
                    </div>
                </div>

                <div class="form-group{{ $errors->has('program_slug') ? ' has-error' : '' }}">
                    <label for="program_slug" class="col-md-4 control-label">Slug</label>

                    <div class="col-md-6">
                        <input id="program_slug" type="text" class="form-control" name="program_slug" value="{{ @$programs->program_slug }}"required>

                        @if ($errors->has('program_slug'))
                            <span class="help-block">
                                <strong>{{ $errors->first('program_slug') }}</strong>
                            </span>
                        @endif
                    </div>
                </div>

                <div class="form-group{{ $errors->has('program_desc') ? ' has-error' : '' }}">
                    <label for="program_desc" class="col-md-4 control-label">Description</label>

                    <div class="col-md-6">
                        <textarea cols="8" rows="8" id="program_desc" type="text" class="form-control" name="program_desc"> {{ @$programs->program_desc }} </textarea>

                        @if ($errors->has('program_desc'))
                            <span class="help-block">
                                <strong>{{ $errors->first('program_desc') }}</strong>
                            </span>
                        @endif
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-8 col-md-offset-4">
                        <button type="submit" class="btn btn-success">
                            @if (@$programs->exists)
                                Update {{ $label }}
                            @else
                                Add {{ $label }}
                            @endif
                        </button>
                        <a class="btn btn-primary" href="{{ route('program.index') }}">Back</a>

                    </div>
                </div>
              </form>

          </div>
        </div>
      </div>
    </div>
  </section>

</div>


@endsection

resources/views/admin/programs/list.blade.php
@extends('layouts.admin.master')

@section('content')
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      List Program
    </h1>
    <ol class="breadcrumb">
      <li><a href="{{ route('dashboard') }}"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Data {{ $label }}</li>
    </ol>
  </section>

  <section class="content">
    <div class="row">
      <div class="col-xs-12">
        <div class="box">
          <div class="box-header">
            <h3 class="box-title">
              <a class="btn btn-success" href="{{ route('program.create') }}">Create New Program</a>
            </h3>
            <div class="box-tools">
              <div class="input-group input-group-sm" style="width: 150px;">
                <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">

                <div class="input-group-btn">
                  <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                </div>
              </div>
            </div>
          </div>
          <!-- /.box-header -->
          <div class="box-body table-responsive">

            @if(Session::has('alert-success'))
              <div class="alert alert-success" style="background-color:#dff0d8 !important; color:#00a65a !important">
                  <strong>{{ \Illuminate\Support\Facades\Session::get('alert-success') }}</strong>
              </div>
            @endif


              <table class="table table-stripped table-hover">
                <thead>
                  <th>#</th>
                  <th>Name</th>
                  <th>Slug</th>
                  <th>Description</th>
                  <th></th>
                </thead>
                <tbody>
                  @php $no = 1; @endphp
                  @foreach ($programs as $program)
                    <tr>
                      <td>{{ $no++ }}</td>
                      <td>{{ $program->program_name }}</td>
                      <td>{{ $program->program_slug }}</td>
                      <td>{{ $program->program_desc }}</td>
                      <td>
                        <form action="{{ route('program.destroy', $program->id) }}" method="post">
                          {{ csrf_field() }}
                          {{ method_field('DELETE') }}
                          <a class="btn btn-sm btn-warning" href="{{ route('program.edit', $program->id) }}">Edit</a>
                          <button class="btn btn-sm btn-danger" type="submit" onclick="return confirm('Yakin ingin menghapus data?')">Delete</button>
                        </form>
                      </td>
                    </tr>
                  @endforeach
                </tbody>
              </table>


          </div>
        </div>
      </div>
    </div>
  </section>

</div>

@endsection