routes/web.php
<?php
// Route::get('/', function () {
//     // return view('welcome');
//     return view('chart');
// });

//Public Routing
Route::get('/chart', 'Admin\DashboardController@chart');
Route::get('/', 'RegisterController@create')->name('signup.create');
Route::post('/signup', 'RegisterController@store')->name('signup.store');
Route::get('/notif', 'NotificationController@index')->name('notif');
Route::get('/odojer_name', function($odojer){
	return View::make('chats')->with('odojer_name', $odojer);
});

Auth::routes();

//Private Routing
Route::group(['middleware' => 'admin'],function(){
  Route::get('/dashboard', 'Admin\DashboardController@index')->name('dashboard');
  Route::resource('group', 'Admin\GroupsController');
	Route::resource('program', 'Admin\ProgramsController');
	Route::resource('city', 'Admin\CitiesController');

  //JSON request
  Route::post('/odojer/filter', 'Admin\OdojersController@filterAll')->name('odojer.filter');
  Route::get('/odojer/column/{column}', 'Admin\OdojersController@getByColumn')->name('odojer.gender');
	Route::resource('odojer', 'Admin\OdojersController');

});

app/Group.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Group extends Model
{
	protected $fillable = [
		'group_name',
		'group_link',
		'group_type',
		'group_program',
		'group_capacity',
		'group_total_now',
		'group_active',

	];

	public function programs()
  {
      return $this->belongsTo('App\Program', 'group_program');
  }

}

app/Http/Controllers/Admin/GroupsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Group;
use App\Program;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Response;

class GroupsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $groups = Group::with('programs')->get();
        return view('admin.groups.list', ['label'=> 'Groups', 'groups' => $groups]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $programs = Program::all();
        return view('admin.groups.form', ['label'=> 'Groups', 'programs' => $programs]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $groups = Group::create([
          'group_name' => $request->group_name,
          'group_link' => $request->group_link,
          'group_type' => $request->group_type,
          'group_program' => $request->group_program,
          'group_capacity' => $request->group_capacity,
          'group_total_now' => 0,
          'group_active' => $request->group_active,
        ]);

        return redirect()->route('group.index')->with('alert-success','Berhasil Menambahkan Data!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $groups = Group::find($id);
        return view('admin.groups.detail', ['label'=> 'Groups', 'groups' => $groups]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $groups = Group::find($id);
        $programs = Program::all();
        return view('admin.groups.form', ['label'=> 'Groups', 'groups' => $groups, 'programs' => $programs]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $groups = Group::find($id);
        $groups->group_name = $request->group_name;
        $groups->group_link = $request->group_link;
        $groups->group_type = $request->group_type;
        $groups->group_program = $request->group_program;
        $groups->group_capacity = $request->group_capacity;
        $groups->group_active = $request->group_active;
        $groups->save();

        return redirect()->route('group.index')->with('alert-success','Berhasil Memperbarui Data!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $group = Group::destroy($id);
        return redirect()->route('group.index')->with('alert-success','Berhasil Menghapus Data!');
    }
}

resources/views/admin/groups/form.blade.php
@extends('layouts.admin.master')

@section('content')
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      @if (@$groups->exists)
          Perbarui Group Whatsapp
      @else
          Tambah Group Whatsapp
      @endif

    </h1>
    <ol class="breadcrumb">
      <li><a href="{{ route('dashboard') }}"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Data {{ $label }}</li>
    </ol>
  </section>

  <section class="content">
    <div class="row">
      <div class="col-xs-12">
        <div class="box">
          <div class="box-header">
            <h3 class="box-title">
            </h3>
            <div class="box-tools">

            </div>
          </div>
          <!-- /.box-header -->
          <div class="box-body">

            @if(@$groups->exists) <?php  $url = route('group.update', @$groups->id); ?>
            @else <?php  $url = route('group.store'); ?>
            @endif
            <form class="form-horizontal" action="{{ $url }}" method="POST">

                  @if (@$groups->exists)
                      {{ method_field('PUT') }}
                  @else
                      {{ method_field('POST') }}
                  @endif

                  {{ csrf_field() }}

                  <div class="form-group{{ $errors->has('group_name') ? ' has-error' : '' }}">
                      <label for="group_name" class="col-md-4 control-label">Nama Group</label>

                      <div class="col-md-6">
                          <input id="group_name" type="text" class="form-control" name="group_name" value="{{ @$groups->group_name }}" required>

                          @if ($errors->has('group_name'))
                              <span class="help-block">
                                  <strong>{{ $errors->first('group_name') }}</strong>
                              </span>
                          @endif
                      </div>
                  </div>

                  <div class="form-group{{ $errors->has('group_link') ? ' has-error' : '' }}">
                      <label for="group_link" class="col-md-4 control-label">Link Group</label>

                      <div class="col-md-6">
                          <input id="group_link" type="text" class="form-control" name="group_link" value="{{ @$groups->group_link }}"required>

                          @if ($errors->has('group_link'))
                              <span class="help-block">
                                  <strong>{{ $errors->first('group_link') }}</strong>
                              </span>
                          @endif
                      </div>
                  </div>
                  <div class="form-group{{ $errors->has('group_type') ? ' has-error' : '' }}">
                      <label for="group_type" class="col-md-4 control-label">Tipe Group</label>

                      <div class="col-md-6">
                        <select class="form-control" name="group_type" required>
                          <?php if (@$groups->group_type == "L"): ?>
                            <option value="L" selected>Laki-Laki</option>
                            <option value="P">Perempuan</option>
                          <?php else: ?>
                            <option value="L">Laki-Laki</option>
                            <option value="P" selected>Perempuan</option>
                          <?php endif; ?>
                        </select>

                          @if ($errors->has('group_type'))
                              <span class="help-block">
                                  <strong>{{ $errors->first('group_type') }}</strong>
                              </span>
                          @endif
                      </div>
                  </div>
                  <div class="form-group{{ $errors->has('group_program') ? ' has-error' : '' }}">
                      <label for="group_program" class="col-md-4 control-label">Program Group</label>

                      <div class="col-md-6">
                          <select class="form-control" name="group_program" required>
                            @foreach(@$programs as $program)
                              <option value="{{$program->id}}" <?php if ($program->id == @$groups->group_program): ?>
                                selected
                              <?php endif; ?>>{{$program->program_slug}}</option>
                            @endforeach
                          </select>

                          @if ($errors->has('group_program'))
                              <span class="help-block">
                                  <strong>{{ $errors->first('group_program') }}</strong>
                              </span>
                          @endif
                      </div>
                  </div>
                  <div class="form-group{{ $errors->has('group_capacity') ? ' has-error' : '' }}">
                      <label for="group_capacity" class="col-md-4 control-label">Kapasitas Group</label>

                      <div class="col-md-6">
                          <input id="group_capacity" capacity="text" class="form-control" name="group_capacity" value="{{ @$groups->group_capacity }}"required>

                          @if ($errors->has('group_capacity'))
                              <span class="help-block">
                                  <strong>{{ $errors->first('group_capacity') }}</strong>
                              </span>
                          @endif
                      </div>
                  </div>
                  <div class="form-group{{ $errors->has('group_active') ? ' has-error' : '' }}">
                      <label for="group_active" class="col-md-4 control-label">Aktif Group</label>

                      <div class="col-md-6">
                        <select class="form-control" name="group_active" required>
                          <?php if (@$groups->group_active == 1): ?>
                            <option value="1" selected>Active</option>
                            <option value="0">Non Active</option>
                          <?php else: ?>
                            <option value="1">Active</option>
                            <option value="0" selected>Non Active</option>
                          <?php endif; ?>
                        </select>

                          @if ($errors->has('group_active'))
                              <span class="help-block">
                                  <strong>{{ $errors->first('group_active') }}</strong>
                              </span>
                          @endif
                      </div>
                  </div>


                  <div class="form-group">
                      <div class="col-md-8 col-md-offset-4">
                          <button type="submit" class="btn btn-success">
                              @if (@$groups->exists)
                                  Update {{ $label }}
                              @else
                                  Add {{ $label }}
                              @endif
                          </button>
                          <a class="btn btn-primary" href="{{ route('group.index') }}">Back</a>
                      </div>
                  </div>
              </form>

          </div>
        </div>
      </div>
    </div>
  </section>

</div>


@endsection

resources/views/admin/groups/list.blade.php
@extends('layouts.admin.master')

@section('content')
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      List Group Whatsapp
    </h1>
    <ol class="breadcrumb">
      <li><a href="{{ route('dashboard') }}"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Data {{ $label }}</li>
    </ol>
  </section>

  <section class="content">
    <div class="row">
      <div class="col-xs-12">
        <div class="box">
          <div class="box-header">
            <h3 class="box-title">
              <a class="btn btn-success" href="{{ route('group.create') }}">Create New Group</a>
            </h3>
            <div class="box-tools">
              <div class="input-group input-group-sm" style="width: 150px;">
                <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">

                <div class="input-group-btn">
                  <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                </div>
              </div>
            </div>
          </div>
          <!-- /.box-header -->
          <div class="box-body table-responsive">

            @if(Session::has('alert-success'))
              <div class="alert alert-success" style="background-color:#dff0d8 !important; color:#00a65a !important">
                  <strong>{{ \Illuminate\Support\Facades\Session::get('alert-success') }}</strong>
              </div>
              <!-- <script>
                  swal({!! Session::get('sweet_alert.alert') !!});
              </script> -->
            @endif

            <table class="table table-stripped table-hover">
              <thead>
                <th>#</th>
                <th>Nama Group</th>
                <th>Link Group</th>
                <th>Tipe Group</th>
                <th>Program Group</th>
                <th>Kapasitas Group</th>
                <th>Total Anggota Sekarang</th>
                <th>Group Aktif</th>
                <th>Opsi</th>
              </thead>
              <tbody>
                @php $no = 1; @endphp
                @foreach ($groups as $group)
                  <tr>
                    <td>{{ $no++ }}</td>
                    <td>{{ $group->group_name }}</td>
                    <td>{{ $group->group_link }}</td>
                    <td>{{ $group->group_type }}</td>
                    <td>{{ $group->programs->program_slug }}</td>
                    <td>{{ $group->group_capacity}}</td>
                    <td>{{ $group->group_total_now }}</td>
                    <td class="text-center">
                      @if($group->group_active == 1)
                        <label class="label label-success">Active</label>
                      @else
                        <label class="label label-danger">Non active</label>
                      @endif
                    </td>
                    <td>
                      <form action="{{ route('group.destroy', $group->id) }}" method="post">
                        {{ csrf_field() }}
                        {{ method_field('DELETE') }}
                        <a class="btn btn-sm btn-warning" href="{{ route('group.edit', $group->id) }}">Edit</a>
                        <button class="btn btn-sm btn-danger" type="submit" onclick="return confirm('Yakin ingin menghapus data?')">Delete</button>
                      </form>
                    </td>
                  </tr>
                @endforeach
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </section>

</div>

@endsection